export const experiences = [
  {
    duration: "July 2025 – Present",
    company: "OvalSoft Technologies",
    title: "Senior Software Engineer",
    website: "https://arrowheadpharmaceuticals.ng/",
    location: "Remote, Abuja, Nigeria",
    descriptions: [
      "Contributed to the design and development of scalable frontend systems used in production, supporting thousands of active users.",
      "Built and maintained reusable UI components using modern JavaScript frameworks, reducing feature development time by 20%.",
      "Collaborated with cross-functional teams (product, backend, QA) to deliver user-focused features, improving delivery timelines by 15%.",
      "Applied testing and debugging practices using Cypress and unit testing tools, reducing frontend defects in production by 25%.",
    ],
    techs: [
      "JavaScript",
      "TypeScript",
      "TailwindCSS",
      "React.js",
      "Next.js",
      "Cypress",
      "GraphQL",
    ],
  },
  {
    duration: "September 2024 – August 2025",
    company: "Sahel AI",
    title: "Frontend Developer (Part-time)",
    website: "https://www.linkedin.com/company/sahel-ai/",
    location: "Dover, DE 19901, USA",
    descriptions: [
      "Developed frontend interfaces for a Legal AI contract analysis platform.",
      "Improved user retention and satisfaction by 25% through UI/UX enhancements.",
      "Worked closely with backend engineers to define APIs, reducing integration issues.",
      "Optimized frontend performance, achieving faster load times and smoother interactions.",
    ],
    techs: [
      "JavaScript",
      "TypeScript",
      "TailwindCSS",
      "React.js",
      "Next.js",
      "Cypress",
      "GraphQL",
    ],
  },
  {
    duration: "July 2022 – April 2025",
    company: "AFEX Commodities Exchange",
    title: "Frontend Developer",
    website: "https://www.linkedin.com/company/afex-commodities-exchange/",
    location: "Abuja, Nigeria",
    descriptions: [
      "Built and maintained fintech platforms supporting commodities trading and payment workflows.",
      "Improved user engagement by 20% through intuitive UI implementation.",
      "Reduced page load times by 30% through performance optimization techniques.",
      "Collaborated with backend teams to improve API reliability and system stability.",
    ],
    techs: [
      "JavaScript",
      "TypeScript",
      "TailwindCSS",
      "React.js",
      "Next.js",
      "Cypress",
      "GraphQL",
    ],
  },
  {
    duration: "May 2022 – July 2024",
    company: "MEV Suite",
    title: "Frontend Developer (Freelance)",
    website: "https://www.linkedin.com/company/mevsuite/",
    location: "Remote, Nigeria",
    descriptions: [
      "Delivered responsive and high-quality user interfaces for client-facing applications.",
      "Optimized state management and component performance for scalable frontend systems.",
      "Worked independently and with distributed teams to deliver features on schedule.",
    ],
    techs: [
      "JavaScript",
      "TypeScript",
      "TailwindCSS",
      "React.js",
      "Next.js",
      "Cypress",
      "GraphQL",
    ],
  },
];

